# -*- coding: utf-8 -*-
"""Does the population size affect murder rates in the US from 1960 to 2012?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fP6o9AcTWYeQ3cKzASKD0OhdXG6L9Ety

Abdelkader Habel 1933311

#QUESTION

I am interested in knowing if the population size in each state in the United States affects murder rates.

#LOADING DATA
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 30)
pd.set_option('precision', 3)
 
# Loading data
crimes_data=pd.read_csv("https://corgis-edu.github.io/corgis/datasets/csv/state_crime/state_crime.csv"
).rename(
    columns={'Data.Population':'Population',
             'Data.Rates.Property.All':'Rate Property',
             'Data.Rates.Property.Burglary':'Rate Burglary',
             'Data.Rates.Property.Larceny':'Rate Larceny',
             'Data.Rates.Property.Motor':'Rate Motor',
             'Data.Rates.Violent.All':'Rate All Violent',
             'Data.Rates.Violent.Assault':'Assault Rate',
             'Data.Rates.Violent.Murder':'Murder Rate',
             'Data.Rates.Violent.Robbery':'Robbery Rate',
             'Data.Rates.Violent.Assault':'Assault Rate',
             'Data.Rates.Violent.Rape':'Rape Rate',
             'Data.Totals.Property.All':'Total Property',
             'Data.Totals.Property.Burglary':'Total Burglary',
             'Data.Totals.Property.Larceny':'Total Larceny',
             'Data.Totals.Property.Motor':'Total Motor',
             'Data.Totals.Violent.All':'Total Violent',
             'Data.Totals.Violent.Assault':'Total Assault',
             'Data.Totals.Violent.Murder':'Total Murder',
             'Data.Totals.Violent.Rape':'Total Rape',
             'Data.Totals.Violent.Robbery':'Total Robbery'
             }
)
crimes_data

"""#ANALYSIS

I want to take the average of all values for the entire period covered (1960-2012).
"""

grouped=crimes_data.groupby(['State']).mean() # gives the mean of all values in the table per state
grouped['Year']=grouped['Year'].map(lambda Year: '1960-2012') #Changes value inside cell from average of the years to the period
grouped['Population']=grouped['Population'].map(lambda Population: Population/1000000) #Gives average pop in millions from 1960-2012
# grouped

country_states=grouped.drop('United States')
# country_states

# country_states.index #make sure data from United States is not here anymore

"""I want a bar plot, just to be able to easily see all the states and their rates. It will not answer my question but will allow me to see the situation better. """

plt.bar(grouped.index,grouped['Murder Rate'])

"""This graph is not readable, not good looking either. """

# Bar plot to see rates per state
plt.figure(figsize=[21,9], dpi=300)


plt.title(
    "Murder Rate per State", 
    fontdict ={
        'family': 'serif',
        'color':  'xkcd:purple',
        'weight': 'bold',
        'size': 22,
    },
    loc='left',
    pad=10
)
# plt.xticks(grouped.index,rotation=90)
plt.bar(grouped.index, grouped['Murder Rate'], color="xkcd:green")
plt.xlabel(
    "State", 
    fontdict ={
        'family': 'serif',
        'color':  'xkcd:black',
        'weight': 'normal',
        'size': 16,
    },
    labelpad=8
)

plt.ylabel(
    "Murder Rate (per 100 000)",
    fontdict ={
        'family': 'serif',
        'color':  'xkcd:black',
        'weight': 'normal',
        'size': 16,
    },
    labelpad=8
)

plt.grid(True, axis='y', alpha=0.5)
plt.hlines(grouped['Murder Rate'].mean(),0,52, alpha=0.3,colors='blue') #Plots a line for the average rate of murder of all states
plt.show()

"""Having all the states in order would be better. Using the state abreviations would allow to distinguish which bar is which state on the x axis. ex: California becomes CA. Also added the country average just to have more info. 


"""

codes=pd.read_csv('https://raw.githubusercontent.com/jasonong/List-of-US-States/master/states.csv')
usa_code={'State':'United States','Abbreviation':'USA'}
state_code=codes.append(usa_code,ignore_index=True).set_index('State')
# state_code

ordered=grouped.sort_values(by='Murder Rate')
# ordered

ordered['Abbreviation']=state_code['Abbreviation']
# ordered

# Bar plot to see rates per state
plt.figure(figsize=[21,9], dpi=300)


plt.title(
    "Murder Rate per State", 
    fontdict ={
        'family': 'serif',
        'color':  'xkcd:purple',
        'weight': 'bold',
        'size': 22,
    },
    loc='left',
    pad=10
)

plt.bar(ordered['Abbreviation'], ordered['Murder Rate'], color="xkcd:green", )
plt.xlabel(
    "State", 
    fontdict ={
        'family': 'serif',
        'color':  'xkcd:black',
        'weight': 'normal',
        'size': 16,
    },
    labelpad=8
)
plt.ylabel(
    "Murder Rate (per 100 000)",
    fontdict ={
        'family': 'serif',
        'color':  'xkcd:black',
        'weight': 'normal',
        'size': 16,
    },
    labelpad=8
)

plt.grid(True, axis='y', alpha=0.5)
plt.hlines(ordered['Murder Rate'].mean(),0,52,alpha=0.3,colors='blue') #Plots a line for the average rate of murder of all states
plt.show()

"""#VISUALIZATION

"""

title_font = {
    'family': 'serif',
    'color':  'xkcd:red purple',
    'weight': 'bold',
    'size': 24,
}
label_font = {
    'family': 'serif',
    'color':  'xkcd:black',
    'weight': 'normal',
    'size': 16,
}

plt.figure(figsize=[21,9], dpi=300)
plt.title(
    "Murder Rates and Population", 
    fontdict=title_font,
    loc='left',
    pad=10
)
plt.xlabel(
    "Population (in millions)",
    fontdict=label_font,
    labelpad=8
)
plt.ylabel(
    "Murder Rate (per 100 000)",
    fontdict=label_font,
    labelpad=8
)
plt.grid(True, axis='both', alpha=0.5)

colours = ["#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462","#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f"]

#Plot
for i, name in enumerate(country_states.index):
  plt.scatter(country_states.at[name, "Population"], country_states.at[name, "Murder Rate"])#, c=colours[i], s=0.5*math.sqrt(data_2012.at[name, "Population"]))
  plt.annotate(name, xy=(country_states.at[name, "Population"], country_states.at[name, "Murder Rate"]),fontsize=12, verticalalignment="center")
plt.hlines(grouped['Murder Rate'].mean(),0,grouped['Population']['California'],alpha=0.3,colors='blue') #Plots a line for the average rate of murder of all states
plt.show()

"""From this graph, we can see that there does not seem to be a correlation between population and murder rates.The light blue line in the graph is the average rate for all states combined.  The largest states in terms of population, like California and New York are not as high on the graph as they would have been if there was a correlation between these two elements. All smaller states are too close to be seen well, we will remove the big states of California, Texas and New York. """

#Drop TX, NY ,CA
small_states=country_states.drop(['Texas','California','New York']) 
# small_states

# Scatter without NY CA TX
title_font = {
    'family': 'serif',
    'color':  'xkcd:red purple',
    'weight': 'bold',
    'size': 24,
}
label_font = {
    'family': 'serif',
    'color':  'xkcd:black',
    'weight': 'normal',
    'size': 16,
}

plt.figure(figsize=[21,9], dpi=300)
plt.title(
    "Murder Rates and Population", 
    fontdict=title_font,
    loc='left',
    pad=10
)
plt.xlabel(
    "Population (in millions)",
    fontdict=label_font,
    labelpad=8
)
plt.ylabel(
    "Murder Rate (per 100 000)",
    fontdict=label_font,
    labelpad=8
)
plt.grid(True, axis='both', alpha=0.5)

colours = ["#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462","#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f"]

#Plot
for i, name in enumerate(small_states.index):
  plt.scatter(small_states.at[name, "Population"], small_states.at[name, "Murder Rate"])
  plt.annotate(name, xy=(small_states.at[name, "Population"], small_states.at[name, "Murder Rate"]),fontsize=12, verticalalignment="center")
plt.hlines(grouped['Murder Rate'].mean(),0,grouped['Population']['Pennsylvania'],alpha=0.3,colors='blue') #Plots a line for the average rate of murder of all states
plt.show()

"""This last graph is even better at showing that there is no correlation between population and murder rates. What is noticeable is that the District of Columbia has had rates that are significantly higher than what the rest of the country has had. If i remove it, the graph will be more readable.

FINAL GRAPH UNDER
"""

#Drop TX, NY ,CA
small_states=country_states.drop(['New York','District of Columbia','Texas','California']) 
# small_states

# Scatter without DC FINAL GRAPH
title_font = {
    'family': 'serif',
    'color':  'xkcd:red purple',
    'weight': 'bold',
    'size': 24,
}
label_font = {
    'family': 'serif',
    'color':  'xkcd:black',
    'weight': 'normal',
    'size': 16,
}

plt.figure(figsize=[21,9], dpi=300)
plt.title(
    "Murder Rates and Population", 
    fontdict=title_font,
    loc='left',
    pad=10
)
plt.xlabel(
    "Population (in millions)",
    fontdict=label_font,
    labelpad=8
)
plt.ylabel(
    "Murder Rate (per 100 000)",
    fontdict=label_font,
    labelpad=8
)
plt.grid(True, axis='both', alpha=0.5)

colours = ["#8dd3c7","#ffffb3","#bebada","#fb8072","#80b1d3","#fdb462","#b3de69","#fccde5","#d9d9d9","#bc80bd","#ccebc5","#ffed6f"]

#Plot
for i, name in enumerate(small_states.index):
  plt.scatter(small_states.at[name, "Population"], small_states.at[name, "Murder Rate"])
  plt.annotate(name, xy=(small_states.at[name, "Population"], small_states.at[name, "Murder Rate"]),fontsize=12, verticalalignment="center")
plt.hlines(grouped['Murder Rate'].mean(),0,grouped['Population']['Pennsylvania'],alpha=0.3,colors='blue') #Plots a line for the average rate of murder of all states
plt.show()

"""FINAL ANSWER: THERE IS NO CORRELATION BETWEEN POPULATION AND MURDER RATES DURING THE 1960-2012 TIME FRAME. """